[build]
  command = "npm install"
  publish = "./"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "./"

[[redirects]]
  from = "/*"
  to = "/app.js"
  status = 200

[build.environment]
  NODE_VERSION = "16"
